library(tidyverse) # Alternatively, library(ggplot2) + library(dplyr)
library(data.table)
library(fields)
library(lubridate)
library(sp)
library(rgdal)
library(gridExtra)

source("R/data_interfaces.R")
source("R/preprocess_discharge.R")
source("R/preprocess_precip.R")
source("R/main_functions.R")
source("R/plot_functions.R")